window._deployTab=0;
window._tunnelTab=0;

function showCopied() { showModal('Copied!','<p>Config copied to clipboard.</p>','<button class="btn btn-primary" onclick="this.closest(\'.modal-overlay\').remove()">OK</button>'); }
function showSaved() { showModal('Saved','<p>Files saved to <code>./terraform/</code></p><div class="terminal-block" style="margin-top:12px;font-size:11px">terraform/<br>├── main.tf<br>├── variables.tf<br>├── outputs.tf<br>└── rawenv-provision.tf</div>','<button class="btn btn-primary" onclick="this.closest(\'.modal-overlay\').remove()">OK</button>'); }

function tfCode() {
  return `<div class="t-muted"># Generated by rawenv from rawenv.toml</div>
<div class="t-muted"># Provider: Hetzner CX22</div><div></div>
<div><span style="color:var(--accent)">resource</span> <span style="color:var(--warning)">"hcloud_server"</span> <span style="color:var(--warning)">"myapp"</span> {</div>
<div>  name        = <span style="color:var(--warning)">"myapp-prod"</span></div>
<div>  server_type = <span style="color:var(--warning)">"cx22"</span></div>
<div>  image       = <span style="color:var(--warning)">"debian-13"</span></div>
<div>  location    = <span style="color:var(--warning)">"fsn1"</span></div>
<div>  ssh_keys    = [<span style="color:var(--accent)">hcloud_ssh_key</span>.default.id]</div>
<div>}</div>`;
}

function ansibleCode() {
  return `<div class="t-muted"># Generated by rawenv — Ansible playbook</div><div></div>
<div>---</div>
<div>- <span style="color:var(--accent)">hosts</span>: production</div>
<div>  <span style="color:var(--accent)">become</span>: true</div>
<div>  <span style="color:var(--accent)">tasks</span>:</div>
<div>    - <span style="color:var(--accent)">name</span>: Install rawenv</div>
<div>      <span style="color:var(--accent)">shell</span>: curl -fsSL rawenv.sh/install | sh</div>
<div>    - <span style="color:var(--accent)">name</span>: Copy config</div>
<div>      <span style="color:var(--accent)">copy</span>: src=rawenv.toml dest=/opt/myapp/rawenv.toml</div>
<div>    - <span style="color:var(--accent)">name</span>: Start services</div>
<div>      <span style="color:var(--accent)">shell</span>: cd /opt/myapp && rawenv up</div>`;
}

function imageBuildCode() {
  return `<div class="t-muted"># Generated Containerfile from rawenv.toml</div><div></div>
<div><span style="color:var(--accent)">FROM</span> debian:13-slim</div>
<div><span style="color:var(--accent)">RUN</span> curl -fsSL rawenv.sh/install | sh</div>
<div><span style="color:var(--accent)">COPY</span> rawenv.toml /app/rawenv.toml</div>
<div><span style="color:var(--accent)">WORKDIR</span> /app</div>
<div><span style="color:var(--accent)">RUN</span> rawenv init --from-toml rawenv.toml</div>
<div><span style="color:var(--accent)">EXPOSE</span> 3000 5432 6379 7700</div>
<div><span style="color:var(--accent)">CMD</span> ["rawenv", "up", "--foreground"]</div>`;
}

function deployLogContent() {
  return `<div style="padding:16px 24px">
    <div style="display:flex;justify-content:space-between;margin-bottom:12px">
      <div><span style="font-weight:600">Deploy Log</span><span class="t-muted" style="font-size:12px;margin-left:8px">Hetzner CX22 · Started 2m ago</span></div>
      <div style="display:flex;gap:6px"><button class="btn btn-sm btn-secondary" style="color:var(--error)">Cancel</button><button class="btn btn-sm btn-secondary">↻ Retry All</button></div>
    </div>
    <div class="progress-bar" style="margin-bottom:16px"><div class="progress-fill" style="width:72%"></div></div>
    <div class="terminal-block" style="max-height:280px;overflow-y:auto;font-size:11px;line-height:1.8">
      <div class="t-success">✓ terraform init — Initializing provider plugins...</div>
      <div class="t-success">✓ terraform plan — 3 resources to create</div>
      <div class="t-success">✓ terraform apply — hcloud_server.myapp created (45s)</div>
      <div class="t-success">✓ SSH connection established — root@46.225.182.233</div>
      <div class="t-success">✓ rawenv installed on remote server</div>
      <div class="t-success">✓ rawenv.toml copied to /opt/myapp/</div>
      <div class="t-success">✓ Node.js 22.15.0 installed</div>
      <div class="t-success">✓ PostgreSQL 18.2 installed</div>
      <div style="color:var(--error)">✗ Redis 7.4 failed: port 6379 already in use</div>
      <div style="margin:8px 0;padding:10px;background:rgba(248,113,113,.1);border:1px solid var(--error);border-radius:6px" id="deploy-error">
        <div style="color:var(--error);font-weight:600;font-size:12px">⚠️ Deployment error</div>
        <div style="color:var(--text-muted);margin-top:4px">Redis failed to start: port 6379 already in use.</div>
        <div style="margin-top:8px;display:flex;gap:6px">
          <button class="btn btn-sm btn-secondary" onclick="document.getElementById('deploy-error').innerHTML='<div class=\\'t-success\\'>✓ AI fix: killed stale redis, rawenv redis started on :6379</div>'">🤖 AI Fix</button>
          <button class="btn btn-sm btn-secondary">Change port</button>
          <button class="btn btn-sm btn-secondary">Skip</button>
          <button class="btn btn-sm btn-secondary">↻ Retry</button>
        </div>
      </div>
    </div>
    <div style="margin-top:12px;padding:12px;background:var(--bg-secondary);border-radius:8px;display:flex;align-items:center;gap:12px">
      <span style="font-size:20px">🤖</span>
      <div style="flex:1;font-size:12px"><div style="font-weight:600;color:var(--accent)">AI Assistant</div><div style="color:var(--text-muted)">Redis port conflict detected. I can kill the stale process or use port 6380. Click "AI Fix" or type below.</div></div>
      <input class="ai-input" placeholder="Tell AI..." style="width:180px;font-size:11px">
    </div>
  </div>`;
}

function renderDeploy() {
  const os=currentOS();
  const tabs=['Terraform','Ansible','Image Build','Deploy Log'];
  const tabHTML=tabs.map((t,i)=>`<div class="tab ${i===window._deployTab?'active':''}" data-testid="deploy-tab-${t.toLowerCase().replace(/\s+/g,'-')}" onclick="window._deployTab=${i};render()">${t}</div>`).join('');

  const contents = [
    `<div class="log-viewer" style="font-size:12px">${tfCode()}</div>
     <div style="padding:12px 24px;display:flex;gap:8px">
       <button class="btn btn-secondary" onclick="showCopied()">📋 Copy Config</button>
       <button class="btn btn-secondary" onclick="showSaved()">💾 Save to terraform/</button>
       <button class="btn btn-primary" onclick="window._deployTab=3;render()">🚀 Deploy Now</button>
     </div>`,
    `<div class="log-viewer" style="font-size:12px">${ansibleCode()}</div>
     <div style="padding:12px 24px;display:flex;gap:8px">
       <button class="btn btn-secondary" onclick="showCopied()">📋 Copy Playbook</button>
       <button class="btn btn-secondary" onclick="showSaved()">💾 Save to ansible/</button>
       <button class="btn btn-primary" onclick="window._deployTab=3;render()">🚀 Run Playbook</button>
     </div>`,
    `<div style="padding:16px 24px">
       <div style="display:flex;gap:16px;margin-bottom:16px">
         <div class="stat-card clickable selected" style="flex:1"><div class="stat-label">Format</div><div class="stat-value" style="font-size:16px">OCI Image</div><div style="font-size:11px;color:var(--text-muted)">Podman/Docker</div></div>
         <div class="stat-card clickable" style="flex:1"><div class="stat-label">Format</div><div class="stat-value" style="font-size:16px">VM Image</div><div style="font-size:11px;color:var(--text-muted)">cloud-init</div></div>
         <div class="stat-card clickable" style="flex:1"><div class="stat-label">Format</div><div class="stat-value" style="font-size:16px">Dockerfile</div><div style="font-size:11px;color:var(--text-muted)">Export only</div></div>
       </div>
       <div class="log-viewer" style="font-size:12px;max-height:220px">${imageBuildCode()}</div>
       <div style="margin-top:12px;display:flex;gap:8px">
         <button class="btn btn-secondary" onclick="showCopied()">📋 Copy</button>
         <button class="btn btn-primary" onclick="window._deployTab=3;render()">🔨 Build Image</button>
       </div>
     </div>`,
    deployLogContent(),
  ];

  return `<div class="screen active"><div class="window ${os}-chrome">${titlebar(os,'rawenv — Deploy')}
    ${breadcrumb([{label:'Dashboard',screen:'gui-dashboard'},{label:'Deploy'}])}
    <div class="gui-layout">${sidebar()}
    <div class="main-content">
      <div class="content-header"><h1>🚀 Deploy</h1><div class="content-meta">Generate configs or deploy directly</div></div>
      <div class="stats-row">
        <div class="stat-card clickable selected"><div class="stat-label">Provider</div><div class="stat-value" style="font-size:18px">Hetzner</div><div style="font-size:11px;color:var(--text-muted)">CX22 · €4.85/mo</div></div>
        <div class="stat-card clickable"><div class="stat-label">Provider</div><div class="stat-value" style="font-size:18px">AWS</div><div style="font-size:11px;color:var(--text-muted)">~$15/mo</div></div>
        <div class="stat-card clickable"><div class="stat-label">Provider</div><div class="stat-value" style="font-size:18px">DigitalOcean</div><div style="font-size:11px;color:var(--text-muted)">$18/mo</div></div>
        <div class="stat-card clickable"><div class="stat-label">Provider</div><div class="stat-value" style="font-size:18px">Custom SSH</div><div style="font-size:11px;color:var(--text-muted)">Any server</div></div>
      </div>
      <div class="tab-bar">${tabHTML}</div>
      ${contents[window._deployTab]}
    </div></div></div></div>`;
}

function renderTunnel() {
  const os=currentOS();
  const tabs=['Active Tunnels','Settings','Logs'];
  const tabHTML=tabs.map((t,i)=>`<div class="tab ${i===window._tunnelTab?'active':''}" data-testid="tunnel-tab-${t.toLowerCase().replace(/\s+/g,'-')}" onclick="window._tunnelTab=${i};render()">${t}</div>`).join('');

  const contents=[
    `<div style="padding:16px 24px">
      <div class="setting-row"><div style="flex:1"><div class="svc-name">utilio.test:3000</div><div style="font-size:11px;color:var(--text-muted)">Node.js dev server</div></div><div style="display:flex;align-items:center;gap:12px"><span class="mono" style="color:var(--success);font-size:12px">https://utilio-3000.rawenv.sh</span><button class="btn btn-sm btn-secondary" onclick="this.textContent='✓';setTimeout(()=>this.textContent='📋',1000)">📋</button>${toggle(true)}</div></div>
      <div class="setting-row"><div style="flex:1"><div class="svc-name">utilio.test:5432</div><div style="font-size:11px;color:var(--text-muted)">PostgreSQL</div></div><div style="display:flex;align-items:center;gap:12px"><span class="mono" style="color:var(--text-disabled);font-size:12px">not tunneled</span>${toggle(false)}</div></div>
      <div class="setting-row"><div style="flex:1"><div class="svc-name">utilio.test:7700</div><div style="font-size:11px;color:var(--text-muted)">Meilisearch</div></div><div style="display:flex;align-items:center;gap:12px"><span class="mono" style="color:var(--text-disabled);font-size:12px">not tunneled</span>${toggle(false)}</div></div>
      <div style="margin-top:12px;padding:12px;background:var(--bg-secondary);border-radius:8px;font-size:12px"><div style="font-weight:600;margin-bottom:4px">Stats</div><div class="t-muted">bore (built-in) · bore.pub · Latency: 12ms · Uptime: 45m · 2.4MB transferred</div></div>
    </div>`,
    `<div style="padding:16px 24px">
      <div class="settings-section"><h3>Provider</h3>
        <div class="setting-row"><div><div class="setting-label">Tunnel provider</div></div><select class="setting-input" style="width:160px"><option>bore (built-in)</option><option>cloudflared</option><option>ngrok</option><option>rathole</option></select></div>
        <div class="setting-row"><div><div class="setting-label">Relay server</div></div><input class="setting-input" value="bore.pub" style="width:160px"></div>
        <div class="setting-row"><div><div class="setting-label">Custom domain</div></div><input class="setting-input" placeholder="tunnel.myapp.com" style="width:200px"></div>
      </div>
      <div class="settings-section"><h3>Security</h3>
        <div class="setting-row"><div><div class="setting-label">Auth required</div></div>${toggle(false)}</div>
        <div class="setting-row"><div><div class="setting-label">IP allowlist</div></div><input class="setting-input" placeholder="1.2.3.4, 5.6.7.8" style="width:200px"></div>
        <div class="setting-row"><div><div class="setting-label">Auto-close</div></div><select class="setting-input" style="width:120px"><option>Never</option><option>30 min</option><option>1 hour</option></select></div>
      </div>
    </div>`,
    `<div style="padding:16px 24px">
      <div style="display:flex;justify-content:space-between;margin-bottom:8px"><span style="font-weight:600">Tunnel Logs</span><div style="display:flex;gap:6px"><button class="btn btn-sm btn-secondary">Clear</button><button class="btn btn-sm btn-secondary">Export</button></div></div>
      <div class="log-viewer" style="height:300px;font-size:11px">
        <div><span class="log-time">14:00:01</span> <span class="log-msg active">Tunnel: localhost:3000 → https://utilio-3000.rawenv.sh</span></div>
        <div><span class="log-time">14:05:12</span> <span class="log-msg normal">GET /api/users → 200 (12ms) [82.135.44.12]</span></div>
        <div><span class="log-time">14:05:14</span> <span class="log-msg normal">POST /api/login → 200 (45ms) [82.135.44.12]</span></div>
        <div><span class="log-time">14:20:44</span> <span class="log-msg warn">Timeout from 91.205.12.8 (blocked)</span></div>
        <div><span class="log-time">14:25:00</span> <span class="log-msg normal">Heartbeat OK · 11ms · 25m uptime</span></div>
        <div><span class="log-time">14:40:18</span> <span class="log-msg active">WebSocket upgrade: /ws → 101</span></div>
        <div><span class="log-time">14:45:00</span> <span class="log-msg normal">Heartbeat OK · ↑2.4MB ↓1.1MB</span></div>
      </div>
      <div style="margin-top:8px;display:flex;justify-content:space-between;font-size:10px;color:var(--text-disabled)"><span>12 requests · 0 errors · 1 blocked</span><span>↑2.4MB ↓1.1MB</span></div>
    </div>`,
  ];

  return `<div class="screen active"><div class="window ${os}-chrome">${titlebar(os,'rawenv — Tunnels')}
    ${breadcrumb([{label:'Dashboard',screen:'gui-dashboard'},{label:'Tunnels'}])}
    <div class="gui-layout">${sidebar()}
    <div class="main-content">
      <div class="content-header"><h1>🔗 Tunnels</h1><div class="content-meta">Expose local services to public URLs</div></div>
      <div class="tab-bar">${tabHTML}</div>
      ${contents[window._tunnelTab]}
    </div></div></div></div>`;
}
