const std = @import("std");
const config = @import("config");

pub fn generatePlaybook(allocator: std.mem.Allocator, cfg: config.Config) ![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(allocator);

    try buf.appendSlice(allocator,
        \\# Generated by rawenv
        \\---
        \\- name: Deploy rawenv environment
        \\  hosts: production
        \\  become: true
        \\  tasks:
        \\    - name: Install rawenv
        \\      shell: curl -fsSL https://rawenv.sh/install | sh
        \\      args:
        \\        creates: /usr/local/bin/rawenv
        \\
        \\    - name: Copy rawenv.toml
        \\      copy:
        \\        src: rawenv.toml
        \\        dest: /opt/rawenv/rawenv.toml
        \\        mode: "0644"
        \\
        \\    - name: Run rawenv up
        \\      command: rawenv up
        \\      args:
        \\        chdir: /opt/rawenv
        \\
    );

    try buf.print(allocator, "  vars:\n    project_name: \"{s}\"\n", .{cfg.project_name});

    return try buf.toOwnedSlice(allocator);
}
