const std = @import("std");
const config = @import("config");

pub fn generateContainerfile(allocator: std.mem.Allocator, cfg: config.Config) ![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(allocator);

    try buf.print(allocator, "# Generated by rawenv — {s}\n", .{cfg.project_name});
    try buf.appendSlice(allocator, 
        \\FROM debian:13-slim
        \\
        \\RUN apt-get update && apt-get install -y curl && \
        \\    curl -fsSL https://rawenv.sh/install | sh && \
        \\    apt-get clean && rm -rf /var/lib/apt/lists/*
        \\
        \\WORKDIR /app
        \\COPY rawenv.toml .
        \\RUN rawenv init
        \\
    );

    for (cfg.services) |svc| {
        if (std.mem.eql(u8, svc.key, "postgresql") or std.mem.eql(u8, svc.key, "postgres")) {
            try buf.appendSlice(allocator, "EXPOSE 5432\n");
        } else if (std.mem.eql(u8, svc.key, "redis")) {
            try buf.appendSlice(allocator, "EXPOSE 6379\n");
        } else if (std.mem.eql(u8, svc.key, "mysql")) {
            try buf.appendSlice(allocator, "EXPOSE 3306\n");
        }
    }

    try buf.appendSlice(allocator, "\nCMD [\"rawenv\", \"up\"]\n");

    return try buf.toOwnedSlice(allocator);
}

pub fn generateVMCloudInit(allocator: std.mem.Allocator, cfg: config.Config) ![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(allocator);

    try buf.appendSlice(allocator, 
        \\#cloud-config
        \\# Generated by rawenv
        \\
        \\package_update: true
        \\packages:
        \\  - curl
        \\
        \\runcmd:
        \\  - curl -fsSL https://rawenv.sh/install | sh
        \\  - mkdir -p /opt/rawenv
        \\  - rawenv init
        \\  - rawenv up
        \\
        \\write_files:
        \\  - path: /opt/rawenv/rawenv.toml
        \\    content: |
        \\
    );

    try buf.print(allocator, "      [project]\n      name = \"{s}\"\n", .{cfg.project_name});

    if (cfg.services.len > 0) {
        try buf.appendSlice(allocator, "      [services]\n");
        for (cfg.services) |svc| {
            try buf.print(allocator, "      {s} = \"{s}\"\n", .{ svc.key, svc.value });
        }
    }

    return try buf.toOwnedSlice(allocator);
}
