const std = @import("std");
const config = @import("config");

pub fn generateContainerfile(allocator: std.mem.Allocator, cfg: config.Config) ![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(allocator);

    try buf.print(allocator, "# Generated by rawenv — {s}\n", .{cfg.project_name});
    try buf.appendSlice(allocator,
        \\# Build stage
        \\FROM debian:13-slim AS build
        \\
        \\RUN apt-get update && apt-get install -y curl && \
        \\    curl -fsSL https://rawenv.sh/install | sh && \
        \\    apt-get clean && rm -rf /var/lib/apt/lists/*
        \\
        \\WORKDIR /app
        \\COPY rawenv.toml .
        \\RUN rawenv init
        \\
        \\# Runtime stage
        \\FROM debian:13-slim
        \\COPY --from=build /usr/local/bin/rawenv /usr/local/bin/rawenv
        \\COPY --from=build /app /app
        \\WORKDIR /app
        \\
    );

    for (cfg.services) |svc| {
        if (std.mem.eql(u8, svc.key, "postgresql") or std.mem.eql(u8, svc.key, "postgres")) {
            try buf.appendSlice(allocator, "EXPOSE 5432\n");
        } else if (std.mem.eql(u8, svc.key, "redis")) {
            try buf.appendSlice(allocator, "EXPOSE 6379\n");
        } else if (std.mem.eql(u8, svc.key, "mysql")) {
            try buf.appendSlice(allocator, "EXPOSE 3306\n");
        } else if (std.mem.eql(u8, svc.key, "node")) {
            try buf.appendSlice(allocator, "EXPOSE 3000\n");
        }
    }

    try buf.appendSlice(allocator, "\nCMD [\"rawenv\", \"up\", \"--foreground\"]\n");

    return try buf.toOwnedSlice(allocator);
}
