const std = @import("std");
const config = @import("config");

pub const Provider = enum { hetzner, aws, digitalocean, custom_ssh };

pub fn generateMainTf(allocator: std.mem.Allocator, cfg: config.Config, provider: Provider) ![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(allocator);
    const w = buf.writer(allocator);

    try w.writeAll("# Generated by rawenv\n");
    try w.print("# Project: {s}\n\n", .{cfg.project_name});

    switch (provider) {
        .hetzner => {
            try w.writeAll(
                \\terraform {
                \\  required_providers {
                \\    hcloud = {
                \\      source  = "hetznercloud/hcloud"
                \\      version = "~> 1.45"
                \\    }
                \\  }
                \\}
                \\
                \\provider "hcloud" {
                \\  token = var.api_token
                \\}
                \\
                \\resource "hcloud_server" "rawenv" {
                \\  name        = var.server_name
                \\  server_type = var.server_type
                \\  image       = "debian-12"
                \\  location    = var.location
                \\
                \\
            );
            try writeProvisioner(w);
            try w.writeAll("}\n");
        },
        .aws => {
            try w.writeAll(
                \\terraform {
                \\  required_providers {
                \\    aws = {
                \\      source  = "hashicorp/aws"
                \\      version = "~> 5.0"
                \\    }
                \\  }
                \\}
                \\
                \\provider "aws" {
                \\  region = var.region
                \\}
                \\
                \\resource "aws_instance" "rawenv" {
                \\  ami           = var.ami
                \\  instance_type = var.instance_type
                \\  key_name      = var.key_name
                \\
                \\
            );
            try writeProvisioner(w);
            try w.writeAll("}\n");
        },
        .digitalocean => {
            try w.writeAll(
                \\terraform {
                \\  required_providers {
                \\    digitalocean = {
                \\      source  = "digitalocean/digitalocean"
                \\      version = "~> 2.0"
                \\    }
                \\  }
                \\}
                \\
                \\provider "digitalocean" {
                \\  token = var.api_token
                \\}
                \\
                \\resource "digitalocean_droplet" "rawenv" {
                \\  name   = var.server_name
                \\  size   = var.droplet_size
                \\  image  = "debian-12-x64"
                \\  region = var.region
                \\
                \\
            );
            try writeProvisioner(w);
            try w.writeAll("}\n");
        },
        .custom_ssh => {
            try w.writeAll(
                \\resource "null_resource" "rawenv" {
                \\  connection {
                \\    type        = "ssh"
                \\    host        = var.ssh_host
                \\    user        = var.ssh_user
                \\    private_key = file(var.ssh_key_path)
                \\  }
                \\
                \\
            );
            try writeProvisioner(w);
            try w.writeAll("}\n");
        },
    }

    return try buf.toOwnedSlice(allocator);
}

fn writeProvisioner(w: anytype) !void {
    try w.writeAll(
        \\  provisioner "remote-exec" {
        \\    inline = [
        \\      "curl -fsSL https://rawenv.sh/install | sh",
        \\      "rawenv up"
        \\    ]
        \\  }
        \\
    );
}

pub fn generateVariablesTf(allocator: std.mem.Allocator, provider: Provider) ![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(allocator);
    const w = buf.writer(allocator);

    try w.writeAll("# Generated by rawenv\n\n");

    switch (provider) {
        .hetzner => try w.writeAll(
            \\variable "api_token" {
            \\  type      = string
            \\  sensitive = true
            \\}
            \\
            \\variable "server_name" {
            \\  type    = string
            \\  default = "rawenv-server"
            \\}
            \\
            \\variable "server_type" {
            \\  type    = string
            \\  default = "cx22"
            \\}
            \\
            \\variable "location" {
            \\  type    = string
            \\  default = "fsn1"
            \\}
            \\
        ),
        .aws => try w.writeAll(
            \\variable "region" {
            \\  type    = string
            \\  default = "us-east-1"
            \\}
            \\
            \\variable "ami" {
            \\  type = string
            \\}
            \\
            \\variable "instance_type" {
            \\  type    = string
            \\  default = "t3.micro"
            \\}
            \\
            \\variable "key_name" {
            \\  type = string
            \\}
            \\
        ),
        .digitalocean => try w.writeAll(
            \\variable "api_token" {
            \\  type      = string
            \\  sensitive = true
            \\}
            \\
            \\variable "server_name" {
            \\  type    = string
            \\  default = "rawenv-server"
            \\}
            \\
            \\variable "droplet_size" {
            \\  type    = string
            \\  default = "s-1vcpu-1gb"
            \\}
            \\
            \\variable "region" {
            \\  type    = string
            \\  default = "nyc1"
            \\}
            \\
        ),
        .custom_ssh => try w.writeAll(
            \\variable "ssh_host" {
            \\  type = string
            \\}
            \\
            \\variable "ssh_user" {
            \\  type    = string
            \\  default = "root"
            \\}
            \\
            \\variable "ssh_key_path" {
            \\  type    = string
            \\  default = "~/.ssh/id_rsa"
            \\}
            \\
        ),
    }

    return try buf.toOwnedSlice(allocator);
}

pub fn generateOutputsTf(allocator: std.mem.Allocator, provider: Provider) ![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(allocator);
    const w = buf.writer(allocator);

    try w.writeAll("# Generated by rawenv\n\n");

    switch (provider) {
        .hetzner => try w.writeAll(
            \\output "server_ip" {
            \\  value = hcloud_server.rawenv.ipv4_address
            \\}
            \\
        ),
        .aws => try w.writeAll(
            \\output "server_ip" {
            \\  value = aws_instance.rawenv.public_ip
            \\}
            \\
        ),
        .digitalocean => try w.writeAll(
            \\output "server_ip" {
            \\  value = digitalocean_droplet.rawenv.ipv4_address
            \\}
            \\
        ),
        .custom_ssh => try w.writeAll(
            \\output "ssh_host" {
            \\  value = var.ssh_host
            \\}
            \\
        ),
    }

    return try buf.toOwnedSlice(allocator);
}
