const std = @import("std");
const config = @import("config");

pub const Provider = enum { hetzner, aws, digitalocean };

pub fn generateTerraform(allocator: std.mem.Allocator, cfg: config.Config, provider: Provider) ![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(allocator);

    try buf.appendSlice(allocator, "# Generated by rawenv\n");
    try buf.print(allocator, "# Project: {s}\n\n", .{cfg.project_name});

    switch (provider) {
        .hetzner => {
            try buf.appendSlice(allocator,
                \\terraform {
                \\  required_providers {
                \\    hcloud = {
                \\      source  = "hetznercloud/hcloud"
                \\      version = "~> 1.45"
                \\    }
                \\  }
                \\}
                \\
                \\variable "api_token" {
                \\  type      = string
                \\  sensitive = true
                \\}
                \\
                \\variable "ssh_key" {
                \\  type = string
                \\}
                \\
                \\provider "hcloud" {
                \\  token = var.api_token
                \\}
                \\
                \\resource "hcloud_server" "rawenv" {
                \\  name        = "rawenv-server"
                \\  server_type = "cx22"
                \\  image       = "debian-13"
                \\  location    = "fsn1"
                \\  ssh_keys    = [var.ssh_key]
                \\}
                \\
            );
        },
        .aws => {
            try buf.appendSlice(allocator,
                \\terraform {
                \\  required_providers {
                \\    aws = {
                \\      source  = "hashicorp/aws"
                \\      version = "~> 5.0"
                \\    }
                \\  }
                \\}
                \\
                \\variable "api_token" {
                \\  type      = string
                \\  sensitive = true
                \\}
                \\
                \\variable "ssh_key" {
                \\  type = string
                \\}
                \\
                \\provider "aws" {
                \\  region = "us-east-1"
                \\}
                \\
                \\resource "aws_instance" "rawenv" {
                \\  ami           = "ami-0c55b159cbfafe1f0"
                \\  instance_type = "t3.small"
                \\  key_name      = var.ssh_key
                \\}
                \\
            );
        },
        .digitalocean => {
            try buf.appendSlice(allocator,
                \\terraform {
                \\  required_providers {
                \\    digitalocean = {
                \\      source  = "digitalocean/digitalocean"
                \\      version = "~> 2.0"
                \\    }
                \\  }
                \\}
                \\
                \\variable "api_token" {
                \\  type      = string
                \\  sensitive = true
                \\}
                \\
                \\variable "ssh_key" {
                \\  type = string
                \\}
                \\
                \\provider "digitalocean" {
                \\  token = var.api_token
                \\}
                \\
                \\resource "digitalocean_droplet" "rawenv" {
                \\  name   = "rawenv-server"
                \\  size   = "s-1vcpu-1gb"
                \\  image  = "debian-13-x64"
                \\  region = "nyc1"
                \\  ssh_keys = [var.ssh_key]
                \\}
                \\
            );
        },
    }

    return try buf.toOwnedSlice(allocator);
}

// Backward-compatible aliases used by src/cli/main.zig
pub const generateMainTf = generateTerraform;

pub fn generateVariablesTf(allocator: std.mem.Allocator, provider: Provider) ![]const u8 {
    _ = allocator;
    _ = provider;
    return "";
}

pub fn generateOutputsTf(allocator: std.mem.Allocator, provider: Provider) ![]const u8 {
    _ = allocator;
    _ = provider;
    return "";
}
